name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear description of what you'd like.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this be useful? What problem does it solve?
    validations:
      required: false
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - CLI
        - Web Dashboard
        - API Server
        - Classification
        - Other
    validations:
      required: true
